### ISSUE TITLE
Dev: Remove `master` branch

### ISSUE THREAD

**Issue by kenjis** [codeigniter4/devkit#126]
The `master` branch only complicates the work and has no benefit.

Currently, the master branch is diverged, `v1.2.0` is not included in `master` or `develop`:
<img width="1392" alt="Screenshot 2024-03-16 9 16 27" src="https://github.com/codeigniter4/devkit/assets/87955/bfb49e31-0e71-4e70-ab15-04a41c8c180d">

**Comment by datamweb** [comment]
Deleted branch **master** was the best choice  in Shield. Simplify and summarize processes.

**Comment by kenjis** [comment]
I don't know why master was diverged, but I would like to do the following:
```console
$ git checkout master 
$ git merge v1.2.0 
Merge made by the 'ort' strategy.
$ git checkout develop 
$ git merge master 
Updating 78caaaf..9d4801f
Fast-forward
$ git branch -D master
```
and will be like this:
<img width="1392" alt="Screenshot 2024-03-16 9 26 58" src="https://github.com/codeigniter4/devkit/assets/87955/7e193c29-af7f-48ad-8336-ee4398a2bcb6">

**Comment by kenjis** [comment]
Done.

Removed `master` 78caaaf043f4ad5e539b2936e1fdf2c89f6f58ce
![Screenshot 2024-03-22 9 38 21](https://github.com/codeigniter4/devkit/assets/87955/7c6becbb-fbbe-480b-b05c-cbcf19f6ab67)
