### ISSUE TITLE
Install Fail

### ISSUE THREAD

**Issue by kadevland** [codeigniter4/devkit#83]
I try to install bu error
i try require codeigniter4/devkit i have : 
Problem 1
    - codeigniter4/devkit[v1.1.0, ..., v1.1.1] require roave/security-advisories dev-latest -> found roave/security-advisories[dev-latest] but it does not match your minimum-stability.
    - Root composer.json requires codeigniter4/devkit ^1.1 -> satisfiable by codeigniter4/devkit[v1.1.0, v1.1.1].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require codeigniter4/devkit:*" to figure out if any version is installable, or "composer require codeigniter4/devkit:^2.1" if you know which you need.

so i try composer require codeigniter4/devkit:1.1.1 and i have :
 Problem 1
    - Root composer.json requires codeigniter4/devkit 1.1.1 -> satisfiable by codeigniter4/devkit[v1.1.1].
    - codeigniter4/devkit v1.1.1 requires roave/security-advisories dev-latest -> found roave/security-advisories[dev-latest] but it does not match your minimum-stability.

**Comment by paulbalandan** [comment]
Hi! Add the following to your composer.json:
```
"minimum-stability": "dev",
"prefer-stable": true,
```
